email:
  url: imap.gmail.com
  login: 
  pwd: 

tempdir: C:/deleteme/

logging:
  level:
    ROOT: DEBUG
    org.springframework: WARN
    javax.activation: WARN
    com.sun.mail: WARN
    javax.mail: WARN
    jdk.event.security: WARN
